//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.Rc
//
#define IDS_HELPFILE                    1
#define IDS_SNAPINDESC                  2
#define IDS_NAME                        3
#define IDS_OWNER_DESC                  4
#define IDS_NAME_DESC                   5
#define IDS_SNAPINNAME                  6
#define IDS_CERT_DESC                   7
#define IDS_Group                       8
#define IDS_GROUP                       8
#define IDS_ABOUTNAME                   9
#define IDS_PST_ROCKET                  10
#define IDS_PST_LANDBASED               11
#define IDS_APPLICATION                 12
#define IDS_APPLICATION_RULE            13
#define IDS_LOG                         14
#define ID_REFRESH_DATABASE             93
#define ID_LOG_PROPERTIES               94
#define ID_DELETE_GROUP                 95
#define ID_DELETE_APPLICATION           96
#define ID_GROUP_PROP                   97
#define ID_ADD_APPLICATION_RULE         98
#define ID_ADD_RESOURCE                 99
#define ID_ADD_GROUP                    100
#define ID_ADD_APPLICATION              101
#define IDD_GROUP                       102
#define IDI_ICON                        108
#define IDI_ICON1                       109
#define IDB_SMOPEN                      111
#define IDB_SMBMP                       112
#define IDB_LGBMP                       113
#define IDD_RESOURCE                    116
#define IDD_RESOURCE1                   117
#define IDD_APPLICATION                 119
#define IDR_SMICONS                     120
#define IDD_APPLICATION_RULE            120
#define IDR_LGICONS                     121
#define IDB_RULE32                      122
#define IDI_ICON2                       125
#define IDD_DIALOG1                     138
#define IDD_LOG_PROPERTY                139
#define IDB_BITMAP1                     140
#define IDI_ICON3                       142
#define IDD_DIALOG_TRIALREQ             143
#define IDB_BITMAP2                     144
#define IDB_BITMAP_LOGO                 144
#define IDD_DIALOG_TRIALEXP             145
#define IDD_DIALOG_SCAN                 146
#define ID_START_SCAN                   147
#define ID_DELETE_UNTRUSTED_FILES       148
#define ID_LABEL_AS_TRUSTED             149
#define IDI_ICON4                       151
#define ID_TERMINATE_ALL                152
#define ID_REFRESH_UNTRUSTED_APPS_LIST  153
#define IDC_ROCKET_NAME                 1000
#define IDC_ROCKET_HEIGHT               1001
#define IDC_ROCKET_WEIGHT               1002
#define IDC_ROCKET_PAYLOAD              1003
#define IDC_ROCKET_STATUS               1005
#define IDC_SECUR                       1009
#define IDC_CHECK_TRIAL_QUERY           1010
#define IDC_RESTYPE                     1011
#define IDC_RADIO_OWNER                 1012
#define IDC_RADIO_NAME                  1013
#define IDC_RADIO_CERT                  1014
#define IDI_REQ_LOGO_TRUST              1014
#define IDC_OWNER_E                     1015
#define IDC_NAME_E                      1016
#define IDC_CERT_E                      1017
#define IDC_OWNER_BROWSE                1018
#define IDC_SCROLLBAR1                  1020
#define IDC_DESCRIPTION                 1021
#define IDC_LOGO                        1022
#define IDC_EDIT1                       1023
#define IDC_GROUPNAME                   1023
#define IDC_PRODUCT_NAME                1024
#define IDC_COMPANY_NAME                1025
#define IDC_PRODUCT_COMP                1025
#define IDC_EDIT_DISPLAYNAME            1026
#define IDC_EDIT2                       1027
#define IDC_EDIT_FILENAME               1027
#define IDC_FILE_BROWSE                 1028
#define IDC_IDENTITYBY                  1029
#define IDC_RADIO_ALLTRUST              1030
#define IDC_RADIO_TRUST                 1031
#define IDC_RADIO_JAIL                  1032
#define IDC_RADIO_UNTRUST               1033
#define IDC_PRODUCT_ICON                1034
#define IDC_RULE_FILE                   1035
#define IDC_RADIO_NOASK                 1035
#define IDC_RADIO_NOPOPUPS              1055
#define IDC_RULE_REGISTRY               1036
#define IDC_RULE_DEVICE                 1037
#define IDC_BUTTON1                     1038
#define IDC_RULE_PERM                   1039
#define IDC_EDIT_RULE                   1040
#define IDC_PRODUCT_DESC                1041
#define IDC_OBJECT_TYPE                 1041
#define IDSTART_TRIAL                   1041
#define IDTRIAL_LATER                   1042
#define IDC_STATIC_APPS_LIST            1045
#define IDPURCHASENOW                   1046
#define IDC_STATIC_APPS_LABEL           1047
#define IDC_CHECK_TO                    1048
#define IDC_DATE_FROM                   1049
#define IDC_STATIC_HT2                  1049
#define IDC_DATE_TO                     1050
#define IDC_STATIC_HT1                  1050
#define IDC_PROGRESS_SCAN               1053
#define IDSTOP                          1054
#define IDB_ROCKET                      40004
#define IDB_CAR                         40005
#define IDB_PLANE                       40006
#define IDB_BIKE                        40007
#define IDB_ROCKET2                     40008
#define IDB_CAR2                        40009
#define IDB_PLANE2                      40010
#define IDB_BIKE2                       40011
#define IDB_CLOSED2                     40012
#define IDB_OPEN2                       40013
#define IDB_CLOSED                      40014
#define IDB_OPEN                        40015

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         40016
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
