//
// GeSWall, Intrusion Prevention System
// 
//
// Created by Andrey Kolishchak
// Copyright (c) 2007-2011 GentleSecurity. All rights reserved.
//
//

#ifndef __ipdevice_h__
#define __ipdevice_h__


#define IOCTL_IP_ECHO_REQUEST                   CTL_CODE(FILE_DEVICE_NETWORK, 0x00, METHOD_BUFFERED, FILE_ANY_ACCESS) 
#define IOCTL_IP_SET_NTE_ADDR_REQUEST           CTL_CODE(FILE_DEVICE_NETWORK, 0x01, METHOD_BUFFERED, FILE_WRITE_ACCESS) 
#define IOCTL_IP_SET_DHCP_NTE                   CTL_CODE(FILE_DEVICE_NETWORK, 0x02, METHOD_BUFFERED, FILE_WRITE_ACCESS) 
#define IOCTL_IP_NOT_SUPPORTED                  CTL_CODE(FILE_DEVICE_NETWORK, 0x03, METHOD_BUFFERED, FILE_WRITE_ACCESS) 
#define IOCTL_IP_SET_FILTER_PTR                 CTL_CODE(FILE_DEVICE_NETWORK, 0x04, METHOD_BUFFERED, FILE_WRITE_ACCESS) 
#define IOCTL_IP_SET_MAP_ROUTE_PTR              CTL_CODE(FILE_DEVICE_NETWORK, 0x05, METHOD_BUFFERED, FILE_WRITE_ACCESS) 
// returns pointer to the IPAddInterface routine in SystemBuffer and IPDelInterface in SystemBuffer + 4 
#define IOCTL_IP_GET_ADD_DELETE_INTERFACE       CTL_CODE(FILE_DEVICE_NETWORK, 0x06, METHOD_BUFFERED, FILE_WRITE_ACCESS) 
#define IOCTL_IP_ADD_DYNAMIC_NTE                CTL_CODE(FILE_DEVICE_NETWORK, 0x07, METHOD_BUFFERED, FILE_WRITE_ACCESS) 
#define IOCTL_IP_DELETE_DYNAMIC_NTE             CTL_CODE(FILE_DEVICE_NETWORK, 0x08, METHOD_BUFFERED, FILE_WRITE_ACCESS) 
#define IOCTL_IP_GET_NTE_INFO                   CTL_CODE(FILE_DEVICE_NETWORK, 0x09, METHOD_BUFFERED, FILE_ANY_ACCESS) 
#define IOCTL_IP_WAKEUP_PATTERN                 CTL_CODE(FILE_DEVICE_NETWORK, 0x0A, METHOD_BUFFERED, FILE_WRITE_ACCESS) 
#define IOCTL_IP_GET_IP_EVENT                   CTL_CODE(FILE_DEVICE_NETWORK, 0x0B, METHOD_BUFFERED, FILE_WRITE_ACCESS) 
// see ipfirewall.h in DDK 
#define IOCTL_IP_SET_FIREWALL_HOOK              CTL_CODE(FILE_DEVICE_NETWORK, 0x0C, METHOD_BUFFERED, FILE_WRITE_ACCESS) 
#define IOCTL_IP_RT_CHANGE_NOTIFY_REQUEST       CTL_CODE(FILE_DEVICE_NETWORK, 0x0D, METHOD_BUFFERED, FILE_ANY_ACCESS) 
#define IOCTL_IP_ADDR_CHANGE_NOTIFY_REQUEST     CTL_CODE(FILE_DEVICE_NETWORK, 0x0E, METHOD_BUFFERED, FILE_ANY_ACCESS) 
#define IOCTL_IP_GET_INTERFACE_INFO             CTL_CODE(FILE_DEVICE_NETWORK, 0x10, METHOD_BUFFERED, FILE_ANY_ACCESS) 
#define IOCTL_IP_GET_BEST_INTERFACE_ID          CTL_CODE(FILE_DEVICE_NETWORK, 0x11, METHOD_BUFFERED, FILE_ANY_ACCESS) 
#define IOCTL_IP_SET_IF_PROMISCUOUS             CTL_CODE(FILE_DEVICE_NETWORK, 0x13, METHOD_BUFFERED, FILE_ANY_ACCESS) 
#define IOCTL_IP_FLUSH_ARP_TABLE                CTL_CODE(FILE_DEVICE_NETWORK, 0x14, METHOD_BUFFERED, FILE_ANY_ACCESS) 
#define IOCTL_IP_GET_IGMP_LIST                  CTL_CODE(FILE_DEVICE_NETWORK, 0x15, METHOD_BUFFERED, FILE_ANY_ACCESS) 
//#define IOCTL_IP_SET_BLOCK_OF_ROUTES          CTL_CODE(FILE_DEVICE_NETWORK, 0x17, METHOD_BUFFERED, FILE_ANY_ACCESS) 
#define IOCTL_IP_RT_CHANGE_NOTIFY_REQUEST_EX    CTL_CODE(FILE_DEVICE_NETWORK, 0x1F, METHOD_BUFFERED, FILE_ANY_ACCESS) 


struct IcmpEchoRequest { 
    ULONG Address; 
    ULONG TimeOut;  // "ping -w" command (in milliseconds) 
    UCHAR b21;      // "ping -r" and "ping -s" commands 
    UCHAR b22; 
    USHORT Size;    // "ping -l" command 
    UCHAR Protocol; // 1 - IPPROTO_ICMP 
    UCHAR Ttl;      // "ping -i" command (Time To Live) 
    UCHAR Tos;      // "ping -v" command (Type Of Service) 
    UCHAR Flags;    // 0x2 - "ping -f" command (IP header flags) 
}; 

#endif // __ipdevice_h__